#!/usr/bin/env bash
set -euo pipefail

system-update-flake
system-rebuild
system-clean
pushd "$NIX_CONFIG_DIR"
git diff --quiet -- programs/zsh.nix || (git commit flake.nix -m 'Update Flake' && git push)
popd
